### ISSUE TITLE
Partie administration

### ISSUE THREAD

**Issue by LucileDT** [LucileDT/quizz-fi#1]
## Liste des pages
- Login
- Liste des proposition
- Ajout de proposition
- Édition de proposition

### Login
- [x] formulaire
  - [x] champ login
  - [x] champ mot de passe
  - [x] bouton valider
- [ ] comportement
  - [ ] à la validation du formulaire, en attente de la validation, gif de loading
  - [ ] si erreur lors de l'authentification, message *"Votre identifiant ou votre mot de passe est invalide, veuillez réessayer"*
  - [ ] si réussite, chargement de la page `Liste des propositions`

### Liste des propositions
- [x] contenu
  - [x] bouton d'ajout de proposition en haut à droite du tableau
  - [x] tableau contenant une proposition par ligne, triées par thème, proposition par défaut
  - [x] pour chaque ligne, bouton d'édition de la proposition
  - [x] pour chaque ligne, bouton de suppression de la proposition
- [x] comportement
  - [x] au clic sur le bouton de création de proposition, chargement de la page de `Création de proposition`
  - [x] au clic sur le bouton d'édition de proposition, chargement de la page de `Modification de proposition`
  - [x] au clic sur le bouton de suppression d'une proposition, ouverture d'une pop up de confirmation *"Voulez-vous réellement supprimer cette proposition ?" "Supprimer" "Annuler"*
    - [x] au clic sur Annuler, fermeture de la pop up
    - [x] au clic sur Supprimer, suppression de la proposition et rechargement de la page `Liste des propositions`

### Ajout de proposition
- [x] Formulaire
  - [x] Liste déroulante Thème*
  - [x] champ Proposition*
  - [x] champ Description complémentaire*
  - [x] champ Numéro de page
- [ ] comportement
  - [x] à la validation du formulaire, enregistrement de la proposition et chargement de la page `Liste des propositions`
  - [ ] en cas d'erreur, affichage du message d'erreur *"Une erreur est survenue : $messageErreur"*

### Édition de proposition
- [x] Formulaire prérempli avec la proposition à éditer
  - [x] Liste déroulante Thème*
  - [x] champ Proposition*
  - [x] champ Description complémentaire*
  - [x] champ Numéro de page
- [ ] comportement
  - [x] à la validation du formulaire, enregistrement des modifications de la proposition et chargement de la page `Liste des propositions`
  - [ ] en cas d'erreur, affichage du message d'erreur *"Une erreur est survenue : $messageErreur"*

**Comment by JulienTant** [comment]
- [x] pas de thème par défaut
- [x] ajouter un * sur les champs obligatoires
