### ISSUE TITLE
[Quizz] Proposition suivante se charge automatiquement 

### ISSUE THREAD

**Issue by Valinssoumis** [LucileDT/quizz-fi#11]
## Page
Réponse aux questions du quizz
`quizz/<seed>`

## Demande
- Est-ce possible de charger automatiquement la question suivante une fois la réponse donné ?
mais en gardant les boutons proposition suivante et précédente

**Comment by LucileDT** [comment]
Je pense que ça va être pénible, car la dernière réponse ne devrait pas activer la soumission du quizz, pour que la personne puisse revenir sur ses réponses précédentes, par exemple.

**Comment by JulienTant** [comment]
En fait c'est pas si pénible que ça à faire, par contre l'experience utilisateur sera "moisi" car un clic changera immediatement tout le contenu de sa page. Alors a moins qu'on ai quelqu'un de chaud pour créer des transitions entre les questions, je pense que c'est une mauvaise idée.

**Comment by Valinssoumis** [comment]
D'accord on laisse tomber alors
