### ISSUE TITLE
[Administration] Affichage complet des propositions dans la liste

### ISSUE THREAD

**Issue by LucileDT** [LucileDT/quizz-fi#12]
## Page
Liste des propositions
`some-secret-zone/questions`

## Demandes
- Dans la liste, afficher en plus de l'aperçu de la question, l'aperçu de la description
- Rajouter le texte complet dans le `title` de l'aperçu de la question et de l'aperçu de la description

## Utilité 
- Ne pas avoir à ouvrir toutes les propositions une à une pour les corriger
- Ne pas avoir à ouvrir toutes les propositions pour vérifier si elles ont une description

**Comment by JulienTant** [comment]
J'ai ajouté un "mode relecture" sur la page d'administration qui ajoute la colonne description et les textes en entier (non formatés en md)
