### ISSUE TITLE
[Administration] Créer un rôle "relecteur" pour les propositions

### ISSUE THREAD

**Issue by LucileDT** [LucileDT/quizz-fi#16]
## Pages
Toute la partie administration

## Demande
- Serait-il possible de créer un rôle "relecteur" pour permettre à des gens d'uniquement consulter la liste des proposition et de vérifier si elles sont bien écrites ? Ils n'auraient pas les droits de création/édition/suppression, juste le droit de lecture.

**Comment by JulienTant** [comment]
Ou alors on fait confiance et on ouvre avec les droits complets.

**Comment by JulienTant** [comment]
Je close pas pour laisser débattre.

**Comment by Valinssoumis** [comment]
Oui je pense que l'on peut donner l'accès à ma connaissance de sram pour réaliser ce travail mais j'aimerai que tu me redonne mes identifiants par mp Discord stp
