### ISSUE TITLE
[Top] Donner le nombre total de réponses positives

### ISSUE THREAD

**Issue by lucasgautheron** [LucileDT/quizz-fi#18]

**Comment by JulienTant** [comment]
ça ressemble à https://github.com/Insoumis/quizz-fi/issues/13  - au mot "positive" près?

**Comment by JulienTant** [comment]
Je laisse @Valinssoumis trancher du coup !

**Comment by Valinssoumis** [comment]
Je pense que comme c'est la actuellement c'est très bien ;) ( c'est bien le nombre de réponses au total actuellement ? )

**Comment by JulienTant** [comment]
Oui

**Comment by Valinssoumis** [comment]
Donc pas besoin de le changer c'est très bien ;)
