### ISSUE TITLE
Partie Quizz - Réponse à une proposition

### ISSUE THREAD

**Issue by LucileDT** [LucileDT/quizz-fi#4]
- [ ] comportement
  - [x] au clic sur le bouton Proposition précédente, chargement de la page `Réponse à une question` précédente
  - [x] au clic sur le bouton Proposition suivante
    - [ ] si l'utilisateur n'a pas choisi de réponse, affichage du message d'erreur *"Vous devez sélectionner une réponse."*
    - [x] si une réponse a été choisie par l'utilisateur, chargement de la page `Réponse à une question` suivante
  - [x] au clic sur le bouton Voir les résultats, enregistrement des préférences de l'utilisateur pour chaque proposition et chargement de la page `Résultat du quizz`
- [x] contenu
  - [x] thème de la proposition
  - [x] proposition
  - [x] description complémentaire de la proposition
  - [x] bouton pour noter la proposition
    - [x] Pas d'accord
    - [x] Plutôt pas d'accord
    - [x] Neutre
    - [x] Plutôt d'accord
    - [x] D'accord
  - [x] bouton Proposition précédente
  - [x] bouton Proposition suivante ou Voir les résultats

**Comment by JulienTant** [comment]
- [ ] au clic sur le bouton Proposition suivante, chargement de la page Réponse à une question suivante *uniquement si la question a une réponse*

**Comment by LucileDT** [comment]
![quizz](https://cloud.githubusercontent.com/assets/23707217/22764853/7debd4a0-ee6d-11e6-97f2-ba8be3758f2f.png)
