### ISSUE TITLE
[Quizz] Redirection laec

### ISSUE THREAD

**Issue by Valinssoumis** [LucileDT/quizz-fi#7]
## Page
Chaque proposition qui apparaît lorsqu'on lance un quizz
`quizz/<seed>`

## Demande
- Ajouter un icone entre l'icone "question 1/10" et "page de l'aec" qui nous sert a rediriger l'utilisateur sur le liens de la proposition sur laec.fr site de tintincastro

Pour l'icone, tintincastro l'avais affiché dans notre chanel, sinon demander a val.

**Comment by JulienTant** [comment]
Merci d'uploader l'image sur github directement (dans cette issue)
