### ISSUE TITLE
[Tout le site] Mail de contact 

### ISSUE THREAD

**Issue by Valinssoumis** [LucileDT/quizz-fi#9]
## Page
Toutes les pages (c'est dans le footer)

## Demande
- ce serait possible de faire un mail contact@suisjeinsoumis.fr et le mettre dans le footer comme dans http://melenchonouimais.fr/programme.html ?

**Comment by LucileDT** [comment]
Faire un mail contact@suisjeinsoumis.fr voudrait dire installer un serveur de mail sur ton site, ce qui peut être pénible à faire et à entretenir, malheureusement.

**Comment by JulienTant** [comment]
On va le faire directement via OVH. Par contre il faudra quelqu'un pour le consulter (pas moi). On le fera ensemble Val

**Comment by Valinssoumis** [comment]
Je m'occupe pour la consultation 😊
